### ISSUE TITLE
Mac OSX All commands throw error

### ISSUE THREAD

**Issue by kkjorsvik** [nanapi/cake-storm#23]
Below is the error:
-----------------------

Argument for @NotNull parameter 'content' of com/intellij/notification/Notification.<init> must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'content' of com/intellij/notification/Notification.<init> must not be null
	at com.intellij.notification.Notification.<init>(Notification.java)
	at com.vexus2.cakestorm.ide.Actions.notification(Actions.java:16)
	at com.vexus2.cakestorm.ide.Actions$SmartJump.actionPerformed(Actions.java:26)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:614)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:663)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.b(IdeKeyEventDispatcher.java:383)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:298)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:217)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:546)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by benjamw** [comment]
I have the same issue on Linux.

2 years and no fix?
